// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(FinalDBContext))]
    [Migration("20240910175913_CriarBancoRennysFinal")]
    partial class CriarBancoRennysFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("emailCadastro")
                        .HasColumnType("longtext");

                    b.Property<string>("nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCadastro")
                        .HasColumnType("longtext");

                    b.Property<string>("senhaCadastro")
                        .HasColumnType("longtext");

                    b.Property<string>("telCadastro")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("backend.Entities.RegistroDePartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<int>("qntDerrota")
                        .HasColumnType("int");

                    b.Property<int>("qntEmpate")
                        .HasColumnType("int");

                    b.Property<int>("qntPartida")
                        .HasColumnType("int");

                    b.Property<int>("qntVitoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("RegistroDePartidas");
                });

            modelBuilder.Entity("backend.Entities.RegistroDePartida", b =>
                {
                    b.HasOne("backend.Entities.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
